### ISSUE TITLE
This needs a new home

### ISSUE THREAD

**Issue by blaise-zaga** [Agent9G/candidate-app#1]
https://github.com/Agent9G/candidate-app/blob/5713df2bc6d8ac075198e3588fd5b389d47d1c6f/src/App.js#L29

**Comment by blaise-zaga** [comment]
What we can do is put it into a constructor or implement the functionality within the shiftArray function.

**Comment by Agent9G** [comment]
So I don't understand the need of a constructor when I'm not using the class component method.

Are you suggesting I nest the above as such?
    
`function shiftArray() {
    let shiftedValue = traits.shift();
    console.log("What has been shifted: ", shiftedValue);
    traits.push(shiftedValue);
    console.log("newArr is: ", traits);
    let changeTrait = (valuePick) => setValue(valuePick); 
    return traits;
  };`

**Comment by blaise-zaga** [comment]
I see you have fixed the problem using another route. However, I don't think you understand the need and usage of a constructor or component lifecycles. Sharing a link to help you understand it better. https://reactjs.org/docs/state-and-lifecycle.html

**Comment by blaise-zaga** [comment]
I will close this issue because this is no longer a concern. Thanks
